dist: bionic
language: java
before_install:
- rm ~/.m2/settings.xml
jdk:
- openjdk11
install: mvn -v
script: mvn -B -nsu verify jacoco:report
cache:
  directories:
  - "$HOME/.m2"
branches:
  except:
  - "/^release\\/.*$/"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: oi6uHnSl9Ct/CgCd742R/mHJq8H0BDG6yzluSYf1tQNbCynZWPimDBwA+NjSZjvOKovCkuIdNzJ15IYrnW/PqZrqCzxyriMfgDacYzgLqhoUpwqJ5OPeTZMlnL4RCiwn8CeKNWBkE5wXaIdnSG6lgyNWedzqwN93nZ8J4D2gVqNtwKm+zGbJSkARbC2g408ys2sSSH/V4rUWq+mYEsTb82eCDtp/tFUKzVycskmb87BnzTQTFw6VgnBEtER9zgOZ2hkxquo+mycWWQkE7ZnyQBqu4dzJqiWqjl671ZznfXldh+9QQoA7OLm0clot8gI+g3zXpJLYL8rslX9U3LYqyropgOcleQRNwvBh9vi1BYckJ2hdW72kRg9iD6fr0nnS/PzHD8+gpIAtbJhNFE1W59IuXKh5IQVYpw27zfaBpl5CJORrbUzOO+ZGeUAahjTMWoJ2a+cBPBYqBb3qEMwCNGwQocymxcbWCn1/vSe5JSZ1Sl/ybl1BfmrG5Ym4ZYTme4H/xcG1+RZUYa53RNtxbPeMN61k7h7Tpk0G8+QcWPlbd/sAKNaqYAYkiGy71ioC1sGsv9VY+D2sDw93PQvHUVYSmEM23fcUX3Ih2IYJoG/KcQ0U9wZQOumxNaPUaJIyyFg0e8jTa4XwbqO8qJrD7gnQ0DI8k6KkI9kTIhI+3gY=
